mhkim90/ssdproject-1234

ssd/CmdHandler.h, ssd/ReadCmdHandler.cpp, ssd/WriteCmdHandler.cpp, unit-test/ssd_command_test.cpp, unit-test/test_main.cpp, unit-test/unit-test.vcxproj
1. 상태 정보
2. 수정/반영내용 : 
add ssd write command handler feature
3. 추가된 (Test된 ) TC 명 :
- SSDCommandTest/WriteTest
- SSDCommandTest/MockWriteTest
4. unit test 전체 Pass 여부 (O)
=> [feature] Add Write Command Handler

test-shell/shell.cpp, test-shell/shell.h, test-shell/test-shell.vcxproj, test-shell/test-shell.vcxproj.filters, unit-test/test_shell.cpp, unit-test/unit-test.vcxproj
1. 상태 정보
2. 반영 내용
- shell.h 파일 명 변경 사항 있습니다. (ㅠㅠ 오타 수정) 
- 파일 추가 : shell.cpp, test_shell.cpp
- Console command line 입력 부분에 대해서 Unit Test 로 시뮬레이션 할 수 있도록 Fixture 반영 했습니다.
3. Unit Test
=> [feature] Shell waitForCommand method

ssd/CmdHandler.h, ssd/ReadCmdHandler.cpp, ssd/WriteCmdHandler.cpp, unit-test/ssd_command_test.cpp
1. 상태 정보
2. 반영 내용
- add ssd read command handler feature
3. Unit Test
- SSDCommandTest/ReadTest
- SSDCommandTest/MockReadTest
=> [feature] Add Read Command Handler

test-shell/command.h, test-shell/command_factory.cpp, test-shell/command_factory.h, test-shell/commnad_factory.h, test-shell/shell.h, test-shell/test-shell.vcxproj, test-shell/test-shell.vcxproj.filters, unit-test/test_factory.cpp, unit-test/test_shell.cpp, unit-test/unit-test.vcxproj
1. 상태 정보
2. 반영 내용
- command_factory unit test 작성하였습니다.
- command factory unit test 통과하도록 command factory class 작성하였습니다.
- 오탈자 일부 수정하였습니다.
3. Unit Test
TestInjectedReadCommand - factory에 주입된 read 명령 call 테스트
TestInjectedWriteCommand - factory에 주입된 write 명령 call 테스트
=> [feature] add command factory with test

test-shell/test-shell.vcxproj.filters
1. 상태 정보
2. 반영 내용
- 비쥬얼 스튜디오 필터 오타 부분 수정하였습니다.
-
-
3. Unit Test
=> [hotfix] fix visual studio file filter

test-shell/ReadCommand.cpp, test-shell/WriteCommand.cpp, test-shell/test-shell.vcxproj, test-shell/test-shell.vcxproj.filters, unit-test/test_shell_read.cpp, unit-test/test_shell_write.cpp, unit-test/unit-test.vcxproj
1. 상태 정보
2. 반영 내용
- write command 추가
- fullwrite command 추가
- read command 의 오타로 인한 컴파일 에러 수정
- 참고로, 중복코드는 다시 한번 리팩토링 하겠습니다.
3. Unit Test
=> Add write/fullwrite command

ssd/CmdHandler.h, ssd/Exception.cpp, ssd/ReadCmdHandler.cpp, ssd/SSDManager.cpp, ssd/WriteCmdHandler.cpp, ssd/ssd.vcxproj, ssd/ssd.vcxproj.filters, unit-test/ssd_command_test.cpp
1. 상태 정보
2. 반영 내용
- add opcode to CmdHandler
- lba range check from CmdHandler, which is base class the other operation checks from each cmd handler type
3. Unit Test
- when write command is issued, data has to be sent together
- when read command is issued, data should not be sent
=> [feature] ssd refactoring - add opcode

test-shell/command_factory.cpp, test-shell/command_factory.h, unit-test/test_factory.cpp, unit-test/test_shell.cpp
1. 상태 정보
2. 반영 내용
- getAllCommands 구현하였습니다.
- getAllCommands를 통해서 shell이 전체 command map을 받을 수 있습니다.
- 테스트 추가하였습니다.
3. Unit Test
TestgetAllCommands
=> [feature] add getAllCommands command

.gitmessage.txt, ssd/CmdHandler.h, ssd/ReadCmdHandler.cpp, ssd/SSDManager.cpp, ssd/WriteCmdHandler.cpp, ssd/ssd.vcxproj, ssd/ssd.vcxproj.filters, unit-test/ssd_command_test.cpp, unit-test/test_main.cpp, unit-test/unit-test.vcxproj
1. 상태 정보
2. 반영 내용
- main에 병합된 feature/ssd 부분 feature/shell에 rebase 하였습니다.
-
-
3. Unit Test
=> ssh, shell feature merge

test-shell/ReadCommand.cpp, unit-test/test_shell_read.cpp
1. 상태 정보
2. 반영 내용
- Full Read Command 구현
- 관련 Test Case 추가
3. Unit Test
=> [feature] fullread command 구현

unit-test/test_shell_read.cpp
1. 상태 정보
2. 반영 내용
- Full Read Execute Testcode 수정
- Test 실행 시 cout 출력 제거
3. Unit Test
=> [hotfix] Fullread Test Code modify

ssd/CmdHandler.h, ssd/FileManager.cpp, ssd/ReadCmdHandler.cpp, ssd/SSDConfig.h, ssd/SSDManager.cpp, ssd/WriteCmdHandler.cpp, ssd/ssd.vcxproj, ssd/ssd.vcxproj.filters, unit-test/ssd_command_test.cpp
1. 상태 정보
2. 반영 내용
- add FileManager.cpp
- Refactoring Read/Write command using FileManager
3. Unit Test
=> [refactoring] ssd refactoring - add FileManager & command refactoring

ssd/main.cpp
1. 상태 정보
2. 반영 내용
- Add main.cpp
3. Unit Test
=> [feature] Add main.cpp

test-shell/WriteCommand.cpp
1. 상태 정보
2. 반영 내용
- command interface 변경에 따른 write/fullwrite command 수정
-
-
3. Unit Test
=> [hotfix] update write command

test-shell/ReadCommand.cpp, unit-test/test_shell_read.cpp
1. 상태 정보
2. 반영 내용
- execute signiture 변경에 따른 read command 수정
3. Unit Test
=> [hotfix] Read Command hotfix

ssd/main.cpp
[hotfix] ssd main modified
1. 상태 (hotfix)
2. 수정/반영내용
modified ssd main
3. 추가된 (Test된 ) TC 명 X
4. Unit Test TC all pass O
=> [hotfix] ssd main modified

ssd/ssd.vcxproj, test-shell/ReadCommand.cpp, test-shell/WriteCommand.cpp, test-shell/command.h, unit-test/test_factory.cpp, unit-test/test_shell_read.cpp, unit-test/test_shell_write.cpp
1. 상태 정보
2. 반영 내용
- ICommand에 execute method 구조 변경
- Issue : https://github.com/mhkim90/ssdproject-1234/issues/14
-
3. Unit Test
=> [hotfix] ICommad 구조 변경 건

test-shell/Printer.cpp, test-shell/ReadCommand.cpp, test-shell/test-shell.vcxproj, test-shell/test-shell.vcxproj.filters, unit-test/test_shell_read.cpp
1. 상태 정보
2. 반영 내용
- Printer Class 추가(Singleton) 및 Read Test 반영
- vs proj 파일 수정 확인 필요!
3. Unit Test
=> [feature] Add Printer Class

test-shell/ReadCommand.cpp
1. 상태 정보
2. 반영 내용
- ReadCommand.cpp compile error 관련 수정
-
-
3. Unit Test
=> [hotfix] ReadCommand compile error 수정

test-shell/TestApp2Command.cpp, test-shell/test-shell.vcxproj, test-shell/test-shell.vcxproj.filters, unit-test/test_shell_testapp2.cpp, unit-test/unit-test.vcxproj
1. 상태 정보
2. 반영 내용
- testapp2 command 추가
- testapp2 관련 unit test 추가
- 추후 다른 command 와 함께 중복코드 리팩토링 예정
3. Unit Test
=> [feature] add testapp2 command

ssd/CmdHandler.h, ssd/CmdHandlerFactory.cpp, ssd/Exception.cpp, ssd/FileManager.cpp, ssd/ReadCmdHandler.cpp, ssd/SSDConfig.h, ssd/SSDManager.cpp, ssd/WriteCmdHandler.cpp, ssd/main.cpp, ssd/ssd.vcxproj, ssd/ssd.vcxproj.filters, unit-test/ssd_command_test.cpp
1. 상태 (refactoring)
2. 수정/반영내용 create command handler using factory
3. 추가된 (Test된 ) TC 명 X
4. Unit Test TC all pass O
1. 상태 정보
2. 반영 내용
-create command handler using factory
-
-
3. Unit Test
=> [refactoring] create command handler using factory

test-shell/WriteCommand.cpp, unit-test/test_shell_write.cpp
1. 상태 정보
2. 반영 내용
- write command refactoring
- fullwrite command 를 write 를 상속 받아서 중복코드 제거
- test case 업데이트
3. Unit Test
=> [refactoring] write/fullwrite command

test-shell/shell.cpp, test-shell/shell.h, unit-test/test_shell.cpp
1. 상태 정보
2. 반영 내용
- Shell run() 추가
- parsingCommandStr() 추가
- help() 추가
3. Unit Test
- COMMAND_RUN_HELP
- COMMAND_RUN_EXIT
- COMMAND_RUN_INVALID_COMMAND_UNKNOWN
- COMMAND_RUN_INVALID_COMMAND_EMPTY
- COMMAND_STR_PARSING
- COMMAND_STR_PARSING_INVALID_ARGUMENT
- WAIT_FOR_COMMAND_READ_READ
- WAIT_FOR_COMMAND_READ_WRITE
=> [feature/shell-shell] Shell 실행 및 command 처리 부분 추가

ssd/CmdHandler.h, unit-test/ssd_command_test.cpp, unit-test/ssd_manager_test.cpp, unit-test/unit-test.vcxproj
1. 상태 정보
2. 반영 내용
- ssd test refactoring
- ssd test, command handler test 분리
3. Unit Test
=> [refatoring] ssd test refactoring

test-shell/TestApp2Command.cpp, unit-test/test_shell_testapp2.cpp
1. 상태 정보
2. 반영 내용
- testapp2 command 리팩토링 하였습니다.
- testapp2 test case 를 수정 하였습니다.
-
3. Unit Test
=> [refactoring]  testapp2

test-shell/main.cpp, test-shell/ssdlib.cpp
1. 상태 정보
2. 반영 내용
- main branch app이 동작하도록 수정하였습니다.
- ssd 빌드후 test-shell 빌드하시면 됩니다.
-
3. Unit Test
=> [hotfix] make test-shell can run

test-shell/ReadCommand.cpp, test-shell/TestApp1Command.cpp, unit-test/test_shell_read.cpp, unit-test/test_shell_testapp1.cpp
1. 상태 정보
2. 반영 내용
- 기존 한글 help 문구를 영어로 변경
3. Unit Test
=> [refactoring] getHelp string value 수정

test-shell/main.cpp
1. 상태 정보
2. 반영 내용
- 추가된 testapp1, testapp2 동작하도록 main 코드 수정하였습니다.
- 리펙토링 예정입니다.
-
3. Unit Test
=> now app can run with testapp command

test-shell/ReadCommand.cpp, test-shell/TestApp1Command.cpp, test-shell/main.cpp, unit-test/test_shell_testapp1.cpp
1. 상태 정보
2. 반영 내용
- testapp1 생성자 변경
3. Unit Test
=> [refactoring] testapp1 생성자 변경

test-shell/command_factory.cpp, test-shell/command_factory.h, test-shell/main.cpp, test-shell/ssdlib.cpp, unit-test/test_factory.cpp, unit-test/test_shell.cpp
1. 상태 정보
2. 반영 내용
- command factory 수정하여 main에서 command inject를 하지않아도 되로록 수정하였습니다.
- issd 를 누가 가지고 있을지에 대해서는 고민해봐야 겠습니다.
-
3. Unit Test
=> refactoring shell main and command factory

logger/ILogger.h, logger/Logger.cpp, logger/Logger.h, logger/logger.vcxproj, logger/logger.vcxproj.filters, ssdproject-1234.sln, unit-test/test_logger.cpp, unit-test/unit-test.vcxproj
1. 상태 정보
2. 반영 내용
- logger 구현위하여 프로젝트 생성하고 코드 뼈대만 만들었습니다.
-
-
3. Unit Test
=> first commit of logger project

test-shell/ReadCommand.cpp, test-shell/TestApp1Command.cpp, test-shell/TestApp2Command.cpp, test-shell/WriteCommand.cpp, test-shell/command.cpp, test-shell/command.h, test-shell/command_factory.cpp, test-shell/main.cpp, test-shell/shell.cpp, test-shell/test-shell.vcxproj, test-shell/test-shell.vcxproj.filters, unit-test/test_shell.cpp, unit-test/test_shell_read.cpp, unit-test/test_shell_testapp1.cpp, unit-test/test_shell_write.cpp
1. 상태 정보
- [] hotfix
2. 반영 내용
- Command 부분 Base Class 반영
- 중복 코드 제거
- throw message 통일 화
3. Unit Test
=> [refactoring] Shell과 Command 관련 중복 코드 제거

ssd/CmdHandler.h, ssd/CmdHandlerFactory.cpp, ssd/EraseCmdHandler.cpp, ssd/FileManager.cpp, ssd/ReadCmdHandler.cpp, ssd/SSDConfig.h, ssd/SSDManager.cpp, ssd/main.cpp, ssd/ssd.vcxproj, unit-test/ssd_command_test.cpp
1. 상태 정보
2. 반영 내용
- add ssd erase command
3. Unit Test
=> [feature] add SSD Erase command

unit-test/test_shell_testapp1.cpp, unit-test/test_shell_testapp2.cpp
1. 상태 정보
2. 반영 내용
- TestApp1 Test Case 수정
- TestApp2 Test Case 수정
-
3. Unit Test
=> [hotfix] UnitTest 오류 부분 수정

test-shell/ssd.h, test-shell/ssdlib.cpp, unit-test/test_shell_read.cpp, unit-test/test_shell_testapp1.cpp, unit-test/test_shell_testapp2.cpp, unit-test/test_shell_write.cpp
1. 상태 정보
2. 반영 내용
- ssd interface 에 erase 추가
- ssd interface 에 flush 추가
- 관련 test mock 수정
- result.txt 확인 할 수 있는 getResult 함수 추가
3. Unit Test
=> [feature] erase, flush 관련 interface 업데이트 

test-shell/ssdlib.cpp
1. 상태 정보
2. 반영 내용
- rebase에 빌드실패하는 이슈 수정하였습니다.
-
-
3. Unit Test
=> fix build failure after rebase

ssd/CmdHandler.h, ssd/CmdHandlerFactory.cpp, ssd/CommandBuffer.cpp, ssd/FileManager.cpp, ssd/FlushCmdHandler.cpp, ssd/SSDConfig.h, ssd/main.cpp, ssd/ssd.vcxproj
[feature] add ssd flush with file manager
1. 상태 (feature)
2. 수정/반영내용
- ssd Flush command with file manager
3. 추가된 (Test된 ) TC 명
4. Unit Test TC all pass
=> add ssd flush with file manager

test-shell/EraseCommand.cpp, test-shell/ReadCommand.cpp, test-shell/command.h, test-shell/command_factory.cpp, test-shell/test-shell.vcxproj, test-shell/test-shell.vcxproj.filters, unit-test/test_shell_read.cpp
1. 상태 정보
2. 반영 내용
- erase command 기능 구현
3. Unit Test
=> [feature] Add Erase Command

unit-test/unit-test.vcxproj
1. 상태 정보
2. 반영 내용
- logger lib을 절대경로로 링크하여 다른 개발자에게서 빌드 에러가 나는 부분 수정하였습니다.
- 현재 다른 부분에서 빌드에러나는 부분은 다른 개발자께서 수정 커밋 PR 예정입니다.
-
3. Unit Test
=> link logger library with relative path

test-shell/EraseRangeCommand.cpp, test-shell/WriteCommand.cpp, test-shell/command_factory.cpp, test-shell/test-shell.vcxproj, test-shell/test-shell.vcxproj.filters, unit-test/test_shell_eraseRange.cpp, unit-test/test_shell_write.cpp, unit-test/unit-test.vcxproj
1. 상태 정보
2. 반영 내용
- erase_range command 를 추가 합니다.
- 관련 unit test 를 추가 합니다.
- fullwrite command 를 통일성 있게 리팩토링 하였습니다.
3. Unit Test
=> [Feature] erase_range command 추가

test-shell/command.h
1. 상태 정보
2. 반영 내용
- Test-shell 의 CommandBase class 에 logger instance 추가
-
-
3. Unit Test
=> [Feature] logger instance 추가

unit-test/test_shell_eraseRange.cpp
1. 상태 정보
2. 반영 내용
- erase range tc 수정
3. Unit Test
=> [hotfix] erase range tc 수정

ssd/CommandBuffer.cpp, ssd/FileManager.cpp
1. 상태 정보
2. 반영 내용
- Optimize command buffer
3. Unit Test
=> [feature] Optimize command buffer

test-shell/main.cpp, test-shell/run_list.lst, test-shell/shell.cpp, test-shell/shell.h, unit-test/run_list.lst, unit-test/test_shell.cpp
1. 상태 정보
2. 반영 내용
- Shell 스크립트 리스트 실행 기능 추가
-
-
3. Unit Test
- ShellFixutre, RUN_SEQUENCE_INVALID_FILE_PATH
- ShellFixutre, LOAD_SEQ
- ShellRunSeqFixutre, RUN_SEQ
=> [feature] Shell 스크립트 리스트 실행 기능 추가

test-shell/EraseCommand.cpp, test-shell/EraseRangeCommand.cpp, test-shell/FlushCommand.cpp, test-shell/ReadCommand.cpp, test-shell/TestApp1Command.cpp, test-shell/TestApp2Command.cpp, test-shell/WriteCommand.cpp
1. 상태 정보
2. 반영 내용
- command class 마다 end log 추가
-
-
3. Unit Test
=> [refactoring] add log

logger/Logger.cpp, logger/Logger.h, ssd/ssd.vcxproj, ssdproject-1234.sln, test-shell/test-shell.vcxproj
1. 상태 정보
2. 반영 내용
- logger의 module name이 모호한 부분이 있어 log directory로 수정하였습니다.
- 다른 project에도 logger lib 링크하도록 수정하였습니다.
-
3. Unit Test
=> rename variable of logger & link logger lib to other projects

ssd/CmdHandler.h, ssd/EraseCmdHandler.cpp, ssd/FlushCmdHandler.cpp, ssd/ReadCmdHandler.cpp, ssd/WriteCmdHandler.cpp
1. 상태 정보
2. 반영 내용
add ssd log
3. Unit Test
=> [feature] add ssd log

test-shell/ssd.h, test-shell/ssdlib.cpp, test-shell/ssdlib.h, unit-test/test_shell.cpp, unit-test/test_shell_eraseRange.cpp, unit-test/test_shell_read.cpp, unit-test/test_shell_testapp1.cpp, unit-test/test_shell_testapp2.cpp, unit-test/test_shell_write.cpp, unit-test/test_ssdlib.cpp
1. 상태 정보
2. 반영 내용
- ssdlib의 중복코드 함수로 추출하여 리펙토링하였습니다.
- 안쓰는 함수 getResult 삭제하였습니다.
-
3. Unit Test
=> refactoring ssdlib by making getAppPath

test-shell/EraseCommand.cpp, test-shell/EraseRangeCommand.cpp, test-shell/FlushCommand.cpp, test-shell/ReadCommand.cpp, test-shell/TestApp1Command.cpp, test-shell/TestApp2Command.cpp, test-shell/WriteCommand.cpp, test-shell/command.cpp, test-shell/command_factory.cpp, test-shell/shell.cpp, test-shell/shell.h, test-shell/ssdlib.cpp, test-shell/ssdlib.h, unit-test/test_main.cpp
1. 상태 정보
2. 반영 내용
- Shell 기능 log 추가
- Throw log 추가
3. Unit Test
=> [feature] Add Shell Logging

.gitignore
1. 상태 정보
2. 반영 내용
- test-shell/ssd.exe 파일 gitignore 추가
-
-
3. Unit Test
=> [refactoring/hotfix] test-shell/ssd.exe 파일 gitignore 추가

unit-test/ssd_command_test.cpp, unit-test/ssd_manager_test.cpp, unit-test/test_commnad_buffer.cpp, unit-test/test_main.cpp
1. 상태 정보
2. 반영 내용
- refactoring 후 ssd 테스트 실패하는 부분 수정하였습니다.
- Issue Link : https://github.com/mhkim90/ssdproject-1234/issues/80
-
3. Unit Test
=> fix ssd test failure

ssd/CommandBuffer.cpp, ssd/CommandBuffer.h, ssd/EraseCmdHandler.cpp, ssd/FileManager.cpp, ssd/FileManager.h
1. 상태 정보
2. 반영 내용
refactoring command buffer with minor fix
불량현상:
https://github.com/mhkim90/ssdproject-1234/issues/74
=> [refactoring] refactoring command buffer

test-shell/ScriptLauncher.cpp, test-shell/ScriptLauncher.h, test-shell/shell.cpp, test-shell/ssdlib.h, test-shell/test-shell.vcxproj, test-shell/test-shell.vcxproj.filters
1. 상태 정보
2. 반영 내용
- Issue Link : https://github.com/mhkim90/ssdproject-1234/issues/82
- SSDLib singleton protect 코드
- Script launcher 관련 h/cpp 추가
3. Unit Test
=> [hotfix/refactoring] Shell Logger 반영 후 TC Fail 수정 및 SSDLib singleton protect 코드 추가

test-shell/EraseCommand.cpp, test-shell/EraseRangeCommand.cpp, test-shell/FlushCommand.cpp, test-shell/ReadCommand.cpp, test-shell/TestApp1Command.cpp, test-shell/TestApp2Command.cpp, test-shell/WriteCommand.cpp, test-shell/ssdlib.cpp
1. 상태 정보
2. 반영 내용
- Log message 수정
3. Unit Test
=> [refactoring] Log message 수정

test-shell/EraseCommand.cpp, test-shell/EraseRangeCommand.cpp, test-shell/ReadCommand.cpp, test-shell/WriteCommand.cpp
1. 상태 정보
2. 반영 내용
- argument parsing error 수정
3. Unit Test
=> [hotfix] argument parsing error 수정

ssd/CmdHandlerFactory.cpp, ssd/CommandBuffer.cpp, ssd/EraseCmdHandler.cpp, ssd/FlushCmdHandler.cpp, ssd/ReadCmdHandler.cpp, ssd/main.cpp
1. 상태 정보
2. 반영 내용
- flush enable
3. Unit Test
=> [hotfix] flush enable

test-shell/ScriptLauncher.cpp, test-shell/ScriptLauncher.h, test-shell/json.hpp, test-shell/test-shell.vcxproj, test-shell/test-shell.vcxproj.filters
1. 상태 정보
2. 반영 내용
- 스크립트 런처 클래스 뼈대
- 아직 사용하는 곳은 없어요~~
-
3. Unit Test
=> 스크립트 런처 클래스 뼈대

ssd/CommandBuffer.cpp
1. 상태 정보
2. 반영 내용
- Erase after write 기능 error fix
3. Unit Test
=> [hotfix] erase command merge fix

test-shell/EraseCommand.cpp, test-shell/EraseRangeCommand.cpp, test-shell/ReadCommand.cpp, test-shell/WriteCommand.cpp
1. 상태 정보
2. 반영 내용
- Log message 수정
3. Unit Test
=> [hotfix] Log message 수정

unit-test/test_factory.cpp
1. 상태 정보
2. 반영 내용
- command factory에서 mocking 옵션이 잘안되어 가끔 테스트 실패하는 부분 수정하였습니다.
-
-
3. Unit Test
=> fix rare failure of unit test

test-shell/ScriptLauncher.cpp, test-shell/ScriptLauncher.h, test-shell/command.cpp, test-shell/command.h, test-shell/command_factory.cpp, test-shell/command_factory.h, unit-test/TestScript1.json, unit-test/test_main.cpp, unit-test/test_shell_script.cpp, unit-test/unit-test.vcxproj, unit-test/unit-test.vcxproj.filters
1. 상태 정보
2. 반영 내용
- 런처 기본 구현
- TC.Script_Launcher_Test, TestScript1
-  아직 TC 단위 동작 테스트 까지 Pass 되었습니다.
3. Unit Test
=> [feature] 스크립트 런처 - TC.Script_Launcher_Test, TestScript1

logger/Logger.cpp, logger/Logger.h
1. 상태 정보
2. 반영 내용
- ssd log에서는 log를 zip으로 바꾸지 못하던 부분 수정하였습니다.
-
-
3. Unit Test
=> fix - now ssd log converts log to zip

test-shell/TestApp1Command.cpp, test-shell/TestApp2Command.cpp, test-shell/seq1.json, unit-test/test_shell.cpp, unit-test/test_shell_testapp1.cpp, unit-test/test_shell_testapp2.cpp
1. 상태 정보
2. 반영 내용
- testapp1 마지막에 flush 추가
- testapp2 마지막에 flush 추가
- seq1 마지막에 flush 추가
3. Unit Test
=> [Feature] 스크립트 업데이트

ssd/ssd.vcxproj, test-shell/ScriptLauncher.cpp, test-shell/ScriptLauncher.h, test-shell/seq1.json, test-shell/shell.cpp, test-shell/test-shell.vcxproj, unit-test/TestScript1.json, unit-test/test_shell_script.cpp, unit-test/unit-test.vcxproj
1. 상태 정보
2. 반영 내용
- script args used option 추가
- proejct 빌드 후 이벤트 옵션 추가 (clean 작업)
-
3. Unit Test
=> [릴리즈] 스크립터 런처 
